name: Publish sonar-scanner docker image

on:
  push:
    paths:
      - "sonar-scanner/**"
    branches:
      - master

env:
  DOCKERFILE_PATH: ./sonar-scanner/
  DOCKER_REPO: docker.io
  IMAGE_ID: kalkanisys/sonar-scanner
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish image
        run: make publish-latest
